# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: canmessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61nmessage.proto\"C\n\nCanMessage\x12\x10\n\x08\x64uration\x18\x01 \x01(\x01\x12\r\n\x05speed\x18\x02 \x01(\x01\x12\x14\n\x0c\x61\x63\x63\x65leration\x18\x03 \x01(\x01\x62\x06proto3')



_CANMESSAGE = DESCRIPTOR.message_types_by_name['CanMessage']
CanMessage = _reflection.GeneratedProtocolMessageType('CanMessage', (_message.Message,), {
  'DESCRIPTOR' : _CANMESSAGE,
  '__module__' : 'canmessage_pb2'
  # @@protoc_insertion_point(class_scope:CanMessage)
  })
_sym_db.RegisterMessage(CanMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CANMESSAGE._serialized_start=20
  _CANMESSAGE._serialized_end=87
# @@protoc_insertion_point(module_scope)
